### ISSUE TITLE
Bank endpoint includes placeholders for items as items of quantity 1

### ISSUE THREAD

**Issue by jjccharles** [llamaXc/osrs-events#1]
Snippet of data from endpoint
![image](https://user-images.githubusercontent.com/20750727/160540532-c5f68984-d510-404d-a69d-7b058ce3520b.png)

Items they correspond to in my bank
![image](https://user-images.githubusercontent.com/20750727/160540563-6252f912-db09-4142-9939-c192bcb0cb4e.png)

Also to confirm its counting placeholders as items of 1 quantity, this is the size of the bank output
![image](https://user-images.githubusercontent.com/20750727/160540694-72daaedf-9b86-491c-ac75-5dc8a781404a.png)

Which matches my bank size
![image](https://user-images.githubusercontent.com/20750727/160540732-0e0f3110-6518-4312-89c2-01098cea77b9.png)

Would be preferable to have the placeholders as quantity 0.

**Comment by BasketBandit** [comment]
Any chance of there being a change for this?

**Comment by llamaXc** [comment]
Thanks for bumping. Yes, I can get a fix out for this. I just tested it and should have a PR out in a day

**Comment by llamaXc** [comment]
Associated [PR](https://github.com/runelite/plugin-hub/pull/2842). Should be merged soon hopefully into Runelite

**Comment by jjccharles** [comment]
I think there may be more to this issue.

My bank can look like this
![image](https://user-images.githubusercontent.com/20750727/178113058-8f6a0c87-5f0d-4651-ac5c-34ffaafe40d7.png)

And it gives me this output
![image](https://user-images.githubusercontent.com/20750727/178113052-44006d63-220d-4645-993f-b1b8f8d5735f.png)

Data output
`
{'playerInfo': {'username': 'MV Frosty', 'combatLevel': 118, 'position': {'x': 1253, 'y': 3741, 'plane': 0}}, 'data': {'value': 239614059, 'items': [{'id': 7936, 'quantity': 131956}, {'id': 13446, 'quantity': 16}, .... , 'timestamp': 1657381635}    
`

When my bank looks like this
![image](https://user-images.githubusercontent.com/20750727/178112996-9a82f177-126e-4829-9135-945c8557795a.png)

The data output I get from the api looks like this.
![image](https://user-images.githubusercontent.com/20750727/178113016-d23f1b79-c5b8-4e9e-837a-45b88c12004e.png)

Data output
`
{'playerInfo': {'username': 'MV Frosty', 'combatLevel': 118, 'position': {'x': 1253, 'y': 3741, 'plane': 0}}, 'data': {'value': 239086235, 'items': [{'id': 19226, 'quantity': 1}, {'id': 13446, 'quantity': 16}, ... , 'timestamp': 1657381664}
`

The item id completely changes, and still shows a value of 1 when just a placeholder. Can validate by trying to cntrl+f the first item id, its just gone.

**Comment by jjccharles** [comment]
I tried a few other items, they get a different item id that still reads the quantity as 1

**Comment by llamaXc** [comment]
I see what you mean, testing it out and now and will resolve it!

**Comment by llamaXc** [comment]
While I am adding this is there anything else you think the bank endpoint should include per item? Name, ge price? I left those out when first making due to size concerns but wanted to see if they might be helpful to you

**Comment by llamaXc** [comment]
Regarding the item id changing that is correct, as placeholder items and normal items have different item ids. The quantity remaining 1 is **incorrect** and was a dumb bug on my part which didn't actually update the quantity for place holder items :/

**Image showing pure ess item id based on whether it is noted, placeholder, or normal item**
<img width="600" alt="Screen Shot 2022-07-09 at 9 39 45 AM" src="https://user-images.githubusercontent.com/11560596/178114950-99d43b86-40cc-4840-832a-6a87b7142ad3.png">

**Comment by jjccharles** [comment]
> While I am adding this is there anything else you think the bank endpoint should include per item? Name, ge price? I left those out when first making due to size concerns but wanted to see if they might be helpful to you

The placeholder item id aspect to the internal workings should be fine, I use some other item api I found and fixed up to lookup items by named and aggregate their various IDs so this shouldn't cause issue.

For context, I use this API for my group iron team so we can use a discord bot command to search all our banks at once. The API pushes the data to a DB which I then have a discord bot command that searches the DB for the item ids related to a given input item name. E.g.
![image](https://user-images.githubusercontent.com/20750727/178131211-fb36ff7b-a2a9-484e-8655-04a3875323a7.png)

I was thinking GE price and high alch value could be nice, I haven't really looked out there too much if there is something in the API I use for any other APIs for getting information about an item like that so it could be better sourced elsewhere to keep these payloads lightweight, unsure really.

One thing that could be good is a way to have the data labelled or organised in someway that the tab it is in can be determined, not sure if that is possible but could be useful for myself since we all use specific bank tabs for our high alchs so can do some own calculations on our total alchs collected.

**Comment by eggins** [comment]
This issue was resolved quite some time ago. Closing for now. :)
