### ISSUE TITLE
Add Section for using osrssocial to README

### ISSUE THREAD

**Issue by ZealotTKO** [llamaXc/osrs-events#2]
Its unclear to me whether osrssocial is a WIP, or in production. I would like to use it, but can't get it to work.

**Comment by preston-meade** [comment]
> Its unclear to me whether osrssocial is a WIP, or in production. I would like to use it, but can't get it to work.

Hello! I was working on a website (osrssocial.com) that leveraged this plugin. But ultimately did not deploy it to a production environment. That being said, the plug-in 'OSRSEvents' can still be used in Runelite for any project you wish to work on. Also feel free to make a PR for any new features that are missing

**Comment by llamaXc** [comment]
Hello! I was working on a website (osrssocial.com) that leveraged this plugin. But ultimately did not deploy it to a production environment. That being said, the plug-in 'OSRSEvents' can still be used in Runelite for any project you wish to work on. Also feel free to make a PR for any new features that are missing

**Comment by ZealotTKO** [comment]
Thanks for the heads up! I would recommend removing the website url from the README then.
